<!DOCTYPE html>
<?php
/**
 * Author: David Jule, October 2020.
 * Process the form generated by index.html and sanitize the input.
 * The amount of cookies is capped at 15 to make the fortune pool more diverse,
 * even though there are more than 50 different fortunes.
 */

$name = filter_input(INPUT_GET, "name", FILTER_SANITIZE_STRING);
$numberOfCookies = filter_input(INPUT_GET, "numberOfCookies", FILTER_VALIDATE_INT);
$colour = $_GET["colour"];
$luckyNumberMin = filter_input(INPUT_GET, "luckyNumberMin", FILTER_VALIDATE_INT);
$luckyNumberMax = filter_input(INPUT_GET, "luckyNumberMax", FILTER_VALIDATE_INT);
#List of all fortunes in an array.
$fortunes = [
    "A beautiful, smart, and loving person will be coming into your life.",
    "A dubious friend may be an enemy in camouflage.",
    "A faithful friend is a strong defense.",
    "A feather in the hand is better than a bird in the air.",
    "A fresh start will put you on your way.",
    "A friend asks only for your time not your money.",
    "Be careful or you could fall for some tricks today.",
    "Beauty in its various forms appeals to you.",
    "Believe it can be done.",
    "Better ask twice than lose yourself once.",
    "Bide your time, for success is near.",
    "Carve your name on your heart and not on marble.",
    "Change is happening in your life, so go with the flow!",
    "Competence like yours is underrated.",
    "Dedicate yourself with a calm mind to the task at hand.",
    "Congratulations! You are on your way.",
    "Courtesy begins in the home.",
    "Do not demand for someone’s soul if you already got his heart.",
    "Do not let ambitions overshadow small success.",
    "Do not make extra work for yourself.",
    "Everyday in your life is a special occasion.",
    "Every flower blooms in its own sweet time.",
    "Good to begin well, better to end well.",
    "Happiness begins with facing life with a smile and a wink.",
    "Happiness will bring you good luck.",
    "Happy life is just in front of you.",
    "Hard words break no bones, fine words butter no parsnips.",
    "Have a beautiful day.",
    "He who expects no gratitude shall never be disappointed.",
    "If you continually give, you will continually have.",
    "If you look in the right places, you can find some good offerings.",
    "If you think you can do a thing or think you can’t do a thing, you’re rig",
    "If your desires are not extravagant, they will be granted.",
    "If your desires are not to extravagant they will be granted.",
    "In order to take, one must first give.",
    "It is better to deal with problems before they arise.",
    "It is honorable to stand up for what is right, however unpopular it seems.",
    "Let the world be filled with tranquility and goodwill.",
    "Like the river flow into the sea. Something are just meant to be.",
    "Love is like sweet medicine, good to the last drop.",
    "Man is born to live and not prepared to live.",
    "Man’s mind, once stretched by a new idea, never regains it’s original dimensions.",
    "Many will travel to hear you speak.",
    "New people will bring you new realizations, especially about big issues.",
    "One can never fill another’s shoes, rather he must outgrow the old shoes.",
    "People find it difficult to resist your persuasive manner.",
    "Pick battles big enough to matter, small enough to win.",
    "Po Says: Pandas like eating bamboo, but I prefer mine dipped in chocolate.",
    "Success is a journey, not a destination.",
    "Success is going from failure to failure without loss of enthusiasm."
];

?>
<html>

<head>
    <title>Fortune Cookies</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        .warning {
            color: red;
        }

        * {
            margin: 0;
        }

        /**Body */
        .info {
            color: black;
            font-weight: bold;
            font-size: 20px;
            margin: auto;
        }

        body {
            margin: auto;
            background-color: #0081AF;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .displaySection {
            background-color: #F7CE5B;
            border-style: solid;
            border-color: #00ABE7;
            width: 75vw;
            height: 90vh;
            text-align: center;
        }


        /**Lists! */

        .listOfCookies {
            justify-items: center;
        }

        ul {
            display: block;
            margin: 0px auto;
        }

        li {
            margin: auto;
            display: block;
            list-style-type: circle;
            background-color: <?= $colour ?>;
            max-width: 400px;
            border-style: solid;
            border-color: black;
            border-radius: 15px;
            height: 60px;
            align-items: center;
            justify-items: center;
            text-align: center;

        }

        /** 
            Hyper links
        */
        a:link, a:active, a:visited{
            text-decoration: none;
            color: <?= $colour ?>;
        }

        a:hover {
            color: white;
        }

    </style>
</head>

<body>

    <section class="displaySection">
        <p class="warning">
            <?php
            if ($name === null) {
                echo "<div>Name not received!</div>";
            }
            if ($luckyNumberMin === null || $luckyNumberMin === false) {
                echo "<div>Lucky number min not received!</div>";
            }
            if ($luckyNumberMax === null || $luckyNumberMax === false) {
                echo "<div>Lucky number max not received!</div>";
            }
            if ($luckyNumberMin >= $luckyNumberMax) {
                echo "<div>You minimun lucky number is greater than the maximum!</div>";
            }
            if ($numberOfCookies === null || $numberOfCookies === false) {
                echo "<div>Number of Cookies not received or invalid</div>";
            }

            /**
             * Generate 7 random numbers using the numbers input by the user.
             * @param min Integer value representing minimum range.
             * @param max Integer value representing maximum range
             * @return String Formated array of numbers
             */
            function generateLuckyNumbers($min,$max){
                $luckyNumbers = [];
                for($j = 0; $j < 7; $j++){
                    array_push($luckyNumbers, rand($min,$max));
                }
                $formatedLuckyNumbers = implode(' | ', $luckyNumbers);

                return $formatedLuckyNumbers;
            }

            ?>
        </p>
        <div>
            <p class="info">Hello, <?= $name ?> </p>
            <p class="info">Your number of cookies are : <?= $numberOfCookies ?></p>
        </div>

        <div>
            <p class="listOfCookies">
                <ul>
                    <?php
                    $listCount = 1;
                    #Generate a cookie and add it to the list.
                    for ($i = 0; $i < $numberOfCookies; $i++) {
                        echo "<li><a href=''>{$listCount}. {$fortunes[rand(0, 49)]}"."<br>
                        Lucky Numbers: ". generateLuckyNumbers($luckyNumberMin,$luckyNumberMax) ."</a></li>";
                        $listCount++;
                    }
                    ?>
                </ul>
                
            </p>
        </div>
    </section>
</body>

</html>